### ISSUE TITLE
How you specify which perl to run?

### ISSUE THREAD

**Issue by dwright** [Nihilus118/perl-debug-adapter#16]
I'm running in an environment that has a system perl and multiple app perls.  I use a custom tool that is very similar to [plenv](https://metacpan.org/release/TOKUHIROM/App-plenv-v1.2.0/view/bin/plenv) to select the perl I want to use from the commandline.   I tried setting up a preLaunchTask in my launch.json to setup my environment prior to running the debugger, but the debugger tried to use the system perl anyway.  Is there a way that I can instruct the Perl debug adapter which perl to use?

**Comment by Nihilus118** [comment]
Yes, it is possible to provide the **perlExecutable** by modifying the launch.json file. You can explicitly specify the path to the desired Perl interpreter in your launch.json configuration.

**Comment by Nihilus118** [comment]
Closing this issue as it appears to be resolved based on the previous guidance. Please feel free to reopen if you need additional assistance.
