### ISSUE TITLE
How to pass arguments (@ARGV) to a perl script

### ISSUE THREAD

**Issue by ccaiyuer** [Nihilus118/perl-debug-adapter#17]
When I use perl-debug-adapter in neovim, I find that there is no place to add args. How can I modify the configuration file in the Readme to pass the parameters?

**Comment by ccaiyuer** [comment]
这是我的nvim的dap.configuration文件配置
![屏幕截图 2024-08-21 002410](https://github.com/user-attachments/assets/0407edd2-7f16-45d3-9207-5e3811136e27)

**Comment by Nihilus118** [comment]
You can set the arguments using the launch.json. For example:
![image](https://github.com/user-attachments/assets/11548fb1-abf7-401a-9264-cbcd30966ab6)

You can find all possible parameters defined inside the [package.json](https://github.com/Nihilus118/perl-debug-adapter/blob/c86b29c24e76f5a0fb88863d46636c68ba4b39ab/package.json#L130) of the project.

**Comment by Nihilus118** [comment]
Closing this issue as it appears to be resolved based on the previous guidance. If you need further assistance, please feel free to reopen the issue. You might also find additional support in the [nvim-dap documentation](https://github.com/mfussenegger/nvim-dap/blob/7ff6936010b7222fea2caea0f67ed77f1b7c60dd/doc/dap.txt#L1317), which provides guidance on configuring the client side when working with debug adapters in general using neovim.
