### ISSUE TITLE
Variables in Comments Get Inline Values As Well

### ISSUE THREAD

**Issue by Alecton4** [Nihilus118/perl-debug-adapter#19]
As the title suggests:

![image](https://github.com/user-attachments/assets/119b1a8c-27ae-41c8-8dbd-9f1ce976cbf8)

**Comment by Nihilus118** [comment]
Great find!
I just fixed this with the latest [commit](https://github.com/Nihilus118/perl-debug-adapter/commit/57cba4a9e1cf3dafd720cd3eba002d403eb6c837). This feature will ship with the next release coming very soon.

**Comment by Nihilus118** [comment]
I've just released a new version that fixes this issue. Please feel free to reopen if the problem persists for you.
