### ISSUE TITLE
`1.0.10` tagged commit

### ISSUE THREAD

**Issue by jthvai** [Nihilus118/perl-debug-adapter#20]
Thank you for your work on this!

![image](https://github.com/user-attachments/assets/293b1e99-09d0-4686-ae6b-06953a26686a)

Please move the `1.0.10` tag to the "release 1.0.10" commit, as that commit contains the correct `package.json` values 🙏🏼

Otherwise, packages that pull from the [versioned tag](https://github.com/Nihilus118/perl-debug-adapter/archive/refs/tags/1.0.10.tar.gz) would build a node app that incorrectly reports itself as v1.0.9.

**Comment by Nihilus118** [comment]
The tag should be fixed and I also recreated the release so it bundles the right source code.

**Comment by jthvai** [comment]
Thank you!
