### ISSUE TITLE
Packaging this extension for other editors

### ISSUE THREAD

**Issue by doronbehar** [Nihilus118/perl-debug-adapter#6]
Hello,

I'd like to package this extension for NixOS, so that other editors will be able to use it. Before even packaging it, I cloned this repo, and tried to run `node dist/extension.js` after `npm run esbuild-base`, and it failed with:

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'vscode'
Require stack:
- /home/doron/repos/vscode-perl-debug/dist/extension.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/doron/repos/vscode-perl-debug/dist/extension.js:1544:23)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/doron/repos/vscode-perl-debug/dist/extension.js' ]
}

Node.js v18.17.1
```

Is there a chance you'd be able to support running this adapter somehow like this?

Tnx,

P.S, it'd be nice to have git tags matched with the version at `package.json`, to make it easy to update this package downstream when releases are published.

**Comment by Nihilus118** [comment]
Hello @doronbehar,

please run `npm install` and `npm compile`.
`npm esbuild-base` is only needed for creating the client side part for VSCode and is not needed for other editors.
Having a look at this [discussion](https://github.com/orgs/perl-ide/discussions/6#discussioncomment-6881142) should help you on setting up the debugger.
I will try to figure out how I can setup GitHub-Actions to manage versions and publish to the VSCode-Marketplace automatically.
I will let you know when I am done.

**Comment by doronbehar** [comment]
Thanks for trying to help @Nihilus118 . The discussion, and specifically [Mason's build recipe](https://github.com/mason-org/mason-registry/blob/2023-09-30-elegant-canada/packages/perl-debug-adapter/package.yaml) helped also.

I think I managed to finally package it successfully. Here's what I had to do:

1. From some reason NixOS' default install phase doesn't install the `out` directory that is generated by `npm run compile`, so I installed it manually. [Here's what our generic builder does for nodejs packages.](https://github.com/NixOS/nixpkgs/blob/feb1cfa3a827902be46ff85bfae5d7647716fe28/pkgs/build-support/node/build-npm-package/hooks/npm-install-hook.sh#L11-L43)
2. I had to manually write a bash script that runs `node <path-to-perl-debugger-directory>/out/debugAdapter.js`.
3. I had to apply the [following patch](https://github.com/Nihilus118/vscode-perl-debug/pull/7), because otherwise I get:

```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '@vscode/debugadapter'
Require stack:
- /nix/store/28yiha0gfnpaa6wx409ab2s44n8n0sjj-perl-debug-adapter-1.0.4/lib/node_modules/perl-debugger/out/perlDebug.js
- /nix/store/28yiha0gfnpaa6wx409ab2s44n8n0sjj-perl-debug-adapter-1.0.4/lib/node_modules/perl-debugger/out/debugAdapter.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/nix/store/28yiha0gfnpaa6wx409ab2s44n8n0sjj-perl-debug-adapter-1.0.4/lib/node_modules/perl-debugger/out/perlDebug.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/nix/store/28yiha0gfnpaa6wx409ab2s44n8n0sjj-perl-debug-adapter-1.0.4/lib/node_modules/perl-debugger/out/perlDebug.js',
    '/nix/store/28yiha0gfnpaa6wx409ab2s44n8n0sjj-perl-debug-adapter-1.0.4/lib/node_modules/perl-debugger/out/debugAdapter.js'
  ]
}

Node.js v18.17.1
```

I haven't tested this adapter on a real Perl script yet, so if I'll experience issues I'll keep you posted :). Thanks for sharing this project and trying to help.

P.S having releases and git tags would be great for us packagers.

**Comment by Nihilus118** [comment]
Great news! Thank you for the effort of bundling the extension! 😄 
I will keep this issue open until I implemented releases in a proper way.

**Comment by doronbehar** [comment]
Thanks :)

Reading [our install script](https://github.com/NixOS/nixpkgs/blob/feb1cfa3a827902be46ff85bfae5d7647716fe28/pkgs/build-support/node/build-npm-package/hooks/npm-install-hook.sh#L11-L43)

I think other improvements are worth suggesting:

1. Using the same `name` key in `package.json` (`perl-debugger`), the same as the repo name on GitHub (`vscode-perl-debug`), and the same as the title of the project on the README (`perl-debug-adapter`), would be nice - as currently NixOS relies on the 1st to decide where to install the node_modules directory (line 11).
2. Not sure how to do that, but making the `out` directory be included in `npm pack` would be nice, as that is what we rely upon to install stuff in `$prefix/lib/node_modules/perl-debugger/`
3. If `package.json` had included a `bin` key, our builder would have automatically included the bash script I described previously.

Thankfully, problems 2 and 3 are easily solvable: https://github.com/Nihilus118/vscode-perl-debug/pull/8 .

As for issue 1, I'll let you take the decision. I personally think `perl-debug-adapter` is the best option.

**Comment by doronbehar** [comment]
One more thing @Nihilus118: After testing this on a real perl script, I noticed nowhere is mentioned that `PadWalker` is required, would be nice to put that in the README as well.

**Comment by Nihilus118** [comment]
I will give it a look @doronbehar. I think I even could get rid of PadWalker by now, it was just an easier way to start the project instead of parsing the variable names on my own.

**Comment by Nihilus118** [comment]
@doronbehar I updated the name of the project, adjusted the README accordingly and published the current state of the project as version [1.0.5](https://github.com/Nihilus118/perl-debug-adapter/releases/tag/1.0.5).
I hope that makes more convenient for you to bundle the extension.

**Comment by doronbehar** [comment]
Thanks @Nihilus118 , everything seems good for packaging 1.0.5 :tada:. It'd be nice for users of other platforms to be able to install this package easily via `npm install -g perl-debug-adapter`. That should be possible if you'd publish the transpiled JS files on npm's registry.

As for the `PadWalker` dependency, maybe you could use [`perl-tree-sitter`](https://github.com/tree-sitter-perl/tree-sitter-perl)? Just throwing an idea, I'm not experienced with this type of development...

**Comment by jthvai** [comment]
I've just made and submitted an AUR (Arch Linux) package [`perl-debug-adapter`](https://aur.archlinux.org/packages/perl-debug-adapter). Since Arch's packaging format is fairly straightforward (bash scripts[^1][^2]), hopefully this will help with packaging for other distros :)

[^1]: [PKGBUILD for `perl-debug-adapter`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=perl-debug-adapter)
[^2]: [ArchWiki](https://wiki.archlinux.org/title/PKGBUILD) and [man](https://man.archlinux.org/man/PKGBUILD.5) pages on PKGBUILDs

**Comment by doronbehar** [comment]
Thanks for linking @jthvai . On my part this issue is resolved :).

**Comment by Nihilus118** [comment]
@jthvai Thank you for your contribution.
